services:
  homeassistant:
    container_name: hass-dyson-test
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./custom_components:/config/custom_components:ro
      - ./docker/ha-config:/config
      - ./docker/logs:/config/logs
    ports:
      - "8124:8123"
    environment:
      - TZ=America/New_York
      - HASS_SERVER_HOST=0.0.0.0
    restart: unless-stopped
    privileged: true

  mosquitto:
    container_name: hass-dyson-mqtt-test
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto:/mosquitto/config:ro
      - ./docker/mosquitto-data:/mosquitto/data
      - ./docker/mosquitto-logs:/mosquitto/log
    restart: unless-stopped
