version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ha-dyson-dev-data:/data
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspaces/${localWorkspaceFolderBasename}
    ports:
      - "8123:8123"
    
  # MQTT broker for testing
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

volumes:
  ha-dyson-dev-data:
